### ISSUE TITLE
Did Ben (benjamn) already push the changes he was talking about?

### ISSUE THREAD

**Issue by seeekr** [lukeadams/meteor#3]
... or make them otherwise available? I think you were saying that those would be important.

I might have some time to invest into this during the next days, so trying to get an understanding of where we are and what needs to be done. Or if we don't fully understand it yet, to attempt to start getting a clearer picture of what it is that we need to understand first :) (Hope that made sense, ha! ;) )

**Comment by seeekr** [comment]
[This is what I am referring to](https://github.com/meteor/meteor/issues/5124#issuecomment-210174338):

> Next steps: after Meteor 1.3.2 is released tomorrow, I'll open a [WORK IN PROGRESS] pull request with the hacky changes I had to make to get this working, and we can continue this discussion on that PR.

**Comment by lukeadams** [comment]
Haha, 3hrs ago
[v4](https://github.com/meteor/meteor/pull/6921)
[v5](https://github.com/meteor/meteor/pull/6922)
[v6](https://github.com/meteor/meteor/pull/6923/commits)
Milestone 1.4 so it's coming fast!
